ALTER TABLE items
    DROP COLUMN IF EXISTS category;
ALTER TABLE items
    ADD COLUMN IF NOT EXISTS category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL;
ALTER TABLE items
    ADD COLUMN IF NOT EXISTS unit VARCHAR(50);

